language: python
python:
  - 3.5
env:
  - TOXENV=py34
  - TOXENV=py35
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
cache:
  - pip
  directories:
    - .tox
deploy: # when pushing release/pypi, upload to pypi
  provider: pypi
  user: amaotone
  on:
    repo: amaotone/fennec
    branch: release/pypi
    destributions: sdist --formats=gztar, zip
  allow_failure: false
