sudo: false
language: python
python:
  - "3.5"
env:
  - TOXENV=py34
  - TOXENV=py35
install:
  - pip install tox --download-cache $HOME/.pip-cache
script:
  - tox -e $TOXENV
cache:
  directories:
    - "$HOME/.pip-cache/"
    - "$HOME/.tox/"
deploy: # when pushing master, upload to pypi
  provider: pypi
  user: amaotone
  on:
    repo: amaotone/fennec
    branch: master
    destributions: sdist --formats=gztar, zip
  allow_failure: false
